### ISSUE TITLE
Building for windows errors..

### ISSUE THREAD

**Issue by antithing** [ethz-asl/libpointmatcher#100]
Hi, I finally got cmake to build the sln, by using a different branch (feature/annealled_outlier_filter), as master would not build. Now though, I am seeing these errors upon trying to build the lib...

Error	5925	error C2039: 'GetNextDocument' : is not a member of 'YAML::Parser'	
Error	5928	error C2039: 'Iterator' : is not a member of 'YAML'	
Error	5934	error C2059: syntax error : ')'	
Error	5929	error C2065: 'Iterator' : undeclared identifier	pointmatcher
Error	7723	error C2065: 'moduleIt' : undeclared identifier	pointmatcher
Error	5931	error C2065: 'moduleTypeIt' : undeclared identifier	
Error	5945	error C2065: 'T' : undeclared identifier	
Error	5932	error C2143: syntax error : missing ')' before '++'	
Error	5948	error C2143: syntax error : missing ';' before '{'	
Error	5944	error C2143: syntax error : missing ';' before '}'	
Error	5936	error C2144: syntax error : 'std::string' should be preceded by ';'	
Error	7728	error C2144: syntax error : 'YAML::Node' should be preceded by ';'	
Error	7722	error C2146: syntax error : missing ';' before identifier 'moduleIt'	
Error	5930	error C2146: syntax error : missing ';' before identifier 'moduleTypeIt'	
Error	5938	error C2228: left of '.first' must have class/struct/union	
Error	5949	error C2447: '{' : missing function header (old-style formal list?)	
Error	31683	error C2593: 'operator =' is ambiguous	
Error	5946	error C2923: 'PointMatcher' : 'T' is not a valid template type argument for parameter 'T'	

in the files ICP.cpp and DataPointsFilter.cpp.

Has anyone successfully built this lib on windows? Please help!

thank you!

**Comment by pomerlef** [comment]
I think you not linking with the appropriate version of yaml-cpp. You should use 0.3 instead of 0.5.
