### ISSUE TITLE
Windows instructions need to replace sections on gtest and yaml....

### ISSUE THREAD

**Issue by drhalftone** [ethz-asl/libpointmatcher#137]
I got through compiling without much issue, but I spent all day trying to link to my Qt project.  After re-compiling everything from scratch several times, I finally figured out what was wrong.  The point matcher source code includes its own versions of gtest and yaml in its contrib folder.  So I do not need, and should not compile these projects separately, yaml, in particular. So by copying the yaml library created inside the build/contribute/yaml/RelWithDeb library into my generate libs directory for all my Qt projects, instead to the YAML library created by the YAML project, I was finally able to link everything.

**Comment by pomerlef** [comment]
I removed the sections about gtest and yaml in [CompilationWindows.md](https://github.com/ethz-asl/libpointmatcher/blob/master/doc/CompilationWindows.md)

with the commit 36464f7bdd742eb4626fefd4327132cba997563e,
