### ISSUE TITLE
"0" coordinate ignored.

### ISSUE THREAD

**Issue by Techmind** [ethz-asl/libpointmatcher#173]
If one of the points have "0" y coordinate(2d matching) it is ignored(does not go to data_in.vtk)
applicable for pcimp, CSV format.

**Comment by pomerlef** [comment]
ok, I'll need more details to investigate that one. Could you attach a simple test file (I guess a CSV point cloud), so I can test on my side?

**Comment by Techmind** [comment]
Sorry, can`t reproduce now(. But i changed my own code and config quite a bit from that time, maybe i made a mistake, or some configuration just filtered this point it out. Just delete this issue for now. Will provide better example if i will re-encounter it.
