### ISSUE TITLE
Problem with PLY read

### ISSUE THREAD

**Issue by arunabh-coderep** [ethz-asl/libpointmatcher#182]
Hi, there is a problem with the loadPLY function as it doesn't contain the option to read a PLY with intensity even though the documentation says so, I checked the code and the property intensity is not written into the loadPLY function hence it gives a segmentation fault when I try to read it.

Thank you!

**Comment by arunabh-coderep** [comment]
[iso_sweep1.ply.zip](https://github.com/ethz-asl/libpointmatcher/files/643478/iso_sweep1.ply.zip)

**Comment by pomerlef** [comment]
I did a simple fix to load PLY files with intensity.

The support for PLY is a bit limited for now and its implementation need to be cleaned. I opened an issue more generic asking for a cleanup, but for now, that's the time I've.

**Comment by pomerlef** [comment]
It should work in the master branch. Just do `git pull`.

**Comment by arunabh-coderep** [comment]
Thank you sir. That worked.
