### ISSUE TITLE
Compile the Source to install but might failed related to YAML 

### ISSUE THREAD

**Issue by weiweikong** [ethz-asl/libpointmatcher#19]
According the issue "installing via PPA crashed apt-get", I planned to compile from the sources. My system is Ubuntu 12.04 with ROS groovy.
1. So I used git, "git clone git://github.com/ethz-asl/libpointmatcher.git" to get the recent sources.
2. Did "cmake.."
   Shoudl I install "GTest" ? or just ignore it?

cmake ..  
-- The C compiler identification is GNU  
-- The CXX compiler identification is GNU  
-- Check for working C compiler: /usr/bin/gcc  
-- Check for working C compiler: /usr/bin/gcc -- works  
-- Detecting C compiler ABI info  
-- Detecting C compiler ABI info - done  
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Doxygen: /usr/local/bin/doxygen 
-- Found DOXYFILE_IN: /home/weiweikong/Downloads/libpointmatcher/Doxyfile.in 
-- Boost version: 1.46.1
-- Found the following Boost libraries:
--   thread
--   filesystem
--   system
--   program_options
--   date_time
-- yaml-cpp found, text-based configuration enabled
-- Looking for _POSIX_TIMERS
-- Looking for _POSIX_TIMERS - found
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
Google test (gtest) not found - Skipping unit tests
-- Configuring done
-- Generating done
-- Build files have been written to:
1. Did "make"
   There are some errors might related to " YAML". I am not quite sure of it. And what should I do with this errors?

Scanning dependencies of target doxygen
[  2%] Writing documentation to /home/weiweikong/Downloads/libpointmatcher/build/doc...
Warning: Tag `SYMBOL_CACHE_SIZE' at line 289 of file /home/weiweikong/Downloads/libpointmatcher/build/Doxyfile has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: Tag`SHOW_DIRECTORIES' at line 473 of file /home/weiweikong/Downloads/libpointmatcher/build/Doxyfile has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: Tag `HTML_ALIGN_MEMBERS' at line 799 of file /home/weiweikong/Downloads/libpointmatcher/build/Doxyfile has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: doxygen no longer ships with the FreeSans font.
You may want to clear or change DOT_FONTNAME.
Otherwise you run the risk that the wrong font is being used for dot generated graphs.
This is pdfTeX, Version 3.1415926-1.40.10 (TeX Live 2009/Debian)
entering extended mode
(./_formulas.tex
LaTeX2e <2009/09/24>
Babel <v3.8l> and hyphenation patterns for english, usenglishmax, dumylang, noh
yphenation, loaded.

[  2%] Built target doxygen
Scanning dependencies of target doc
[  2%] Built target doc
Scanning dependencies of target pointmatcher
[  5%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/Logger.cpp.o
In file included from /home/weiweikong/Downloads/libpointmatcher/pointmatcher/PointMatcher.h:58:0,
                 from /home/weiweikong/Downloads/libpointmatcher/pointmatcher/Logger.cpp:36:
/home/weiweikong/Downloads/libpointmatcher/pointmatcher/Registrar.h: In member function ‘Interface\* PointMatcherSupport::Registrar<Interface>::createFromYAML(const YAML::Node&) const’:
/home/weiweikong/Downloads/libpointmatcher/pointmatcher/Registrar.h:176:19: error: ‘const class YAML::Node’ has no member named ‘to’
/home/weiweikong/Downloads/libpointmatcher/pointmatcher/Registrar.h:176:33: error: expected primary-expression before ‘>’ token
/home/weiweikong/Downloads/libpointmatcher/pointmatcher/Registrar.h:176:35: error: expected primary-expression before ‘)’ token
/home/weiweikong/Downloads/libpointmatcher/pointmatcher/Registrar.h:181:5: error: ‘Iterator’ is not a member of ‘YAML’
/home/weiweikong/Downloads/libpointmatcher/pointmatcher/Registrar.h:181:20: error: expected ‘;’ before ‘mapIt’
/home/weiweikong/Downloads/libpointmatcher/pointmatcher/Registrar.h:182:5: error: ‘mapIt’ was not declared in this scope
/home/weiweikong/Downloads/libpointmatcher/pointmatcher/Registrar.h:183:9: error: ‘Iterator’ is not a member of ‘YAML’
/home/weiweikong/Downloads/libpointmatcher/pointmatcher/Registrar.h:183:24: error: expected ‘;’ before ‘paramIt’
/home/weiweikong/Downloads/libpointmatcher/pointmatcher/Registrar.h:183:58: error: ‘paramIt’ was not declared in this scope
make[2]: **\* [CMakeFiles/pointmatcher.dir/pointmatcher/Logger.cpp.o] Error 1
make[1]: **\* [CMakeFiles/pointmatcher.dir/all] Error 2
make: **\* [all] Error 2
1. However, I download the libpointmatcher from http://freecode.com/projects/libpointmatcher. 

I could successfully build it.

I will took part in the SSRR 2013 Rescue Camp, so I would like to test libpointmatcher before. However, I am not quite familiar with it, and tried different ways but still get the above erorrs.

Thanks!

**Comment by xlla** [comment]
How to migrate to yaml-cpp 0.5 if my ROS is work with new version.
