### ISSUE TITLE
Scale change between the clouds (point-to-plane ICP)

### ISSUE THREAD

**Issue by alexsmartens** [ethz-asl/libpointmatcher#196]
Hi, my point clouds are in different scale. I am looking for a tool for non-rigid transformation. The libpointmatcher tutorial says that point-to-plane ICP is able to solve not only for a rigid transform, but also for a scale change between the clouds.
I tested the program on my clouds with PointToPlaneErrorMinimizer and PointToPointErrorMinimizer. The transformation matrices are a bit different but the scale has not really changed. Should I enable the scale transformation somewhere?
Thanks a lot for your help!

**Comment by pomerlef** [comment]
You need to use `PointToPointSimilarityErrorMinimizer`.

See [this answer](https://github.com/ethz-asl/libpointmatcher/issues/188#issuecomment-270960696) for an example.
