### ISSUE TITLE
#error Eigen2-support

### ISSUE THREAD

**Issue by talregev** [ethz-asl/libpointmatcher#207]
I compile the code with ubutnu-16-04 and it has Eigen 3.2.92 by default. 
I get this error:
```c++
#error Eigen2-support is only available up to version 3.2. Please go to "http://eigen.tuxfamily.org/index.php?title=Eigen2" for further information`
```
I am using 1.2.3 release version from [here][3].
Can you release a new version without this [define][2]?  
Compile with the latest code on [master][1] solve that issue. 

Regards,
Tal Regev.

[1]:https://github.com/ethz-asl/libpointmatcher/blob/master/pointmatcher/PointMatcher.h#L42
[2]:https://github.com/ethz-asl/libpointmatcher/blob/release/1.2.3/pointmatcher/PointMatcher.h#L42
[3]:https://github.com/ethz-asl/libpointmatcher/releases

**Comment by pomerlef** [comment]
Alright, thanks for reporting. Using the `master` branch was indeed the good thing to do. We are waiting a bit for a new release because some compilation issues still need to be resolved. 

I'll add a message on the release 1.2.3 the highlight that it only work for Eigen 3.2.
