### ISSUE TITLE
ICPSequence reprocesses mapPointCloud every registration

### ISSUE THREAD

**Issue by lorenwel** [ethz-asl/libpointmatcher#209]
When using an `ICPSequence` every time the compute function is called the `mapPointCloud` gets copied and filtered and the KDTree is rebuilt. 
This slows registration against large point clouds down significantly, e.g. when localizing against a large, static map.
This code was introduced in #57.

Shouldn't this code be moved to the `setMap(...)` function, since this function is required to be called before registering, anyway?
I understand that you might not want `mapPointCloud` to be a filtered map, since we might want to retrieve the map again at a later point. 
In this case an additional member could be added to the `ICPSequence` struct to store the filtered map.
This shouldn't increase memory usage, since in the current state, a filtered copy of the map is created as well. 

Am I missing a reason why we want to reprocess the map every time we register a reading point cloud?
If not and you agree this is an issue, I can open a pull request.

**Comment by pomerlef** [comment]
You're right. The kd-tree shouldn't be rebuilt at every use and filtering should happen outside. 

If you've a pull request to fix it, I would be happy to look at it.

Thanks for reporting!
