### ISSUE TITLE
Install rule issue

### ISSUE THREAD

**Issue by artivis** [ethz-asl/libpointmatcher#213]
Hi,

I have a Travis job for a package that depends on `libpointmatcher`  (`ros-indigo-libpointmatcher`) which fails building with the following error :  
```terminal
No rule to make target `/tmp/binarydeb/ros-indigo-libpointmatcher-1.2.3/contrib/yaml-cpp-pm/include'
```

The Travis job can be found [here](https://travis-ci.org/artivis/laser_odometry_libpointmatcher/jobs/236428446).

Any idea ?

**Comment by pomerlef** [comment]
Was is working before and now it fails? Is so, it would help to know when it crashes to track the problem.

**Comment by artivis** [comment]
No it never worked as it is a job that I very recently set up. I'll see if I can reproduce the error on my machine and/or get more detailed info.

**Comment by artivis** [comment]
I couldn't reproduce exactly the same error logs on my machine but it might be due to the fact that I also depends on [`pointmatcher_ros`](https://github.com/ethz-asl/pointmatcher-ros) which misses a dependency on `libpointmatcher`.  
See [`pointmatcher_ros` PR 1](https://github.com/ethz-asl/pointmatcher-ros/pull/1).
