### ISSUE TITLE
Reflection Matrix in PointToPointCovErrorMinimizer

### ISSUE THREAD

**Issue by pierrefranklin** [ethz-asl/libpointmatcher#215]
Taken directly from the code in PointToPointErrorMinimizer::compute(...):

```
// It is possible to get a reflection instead of a rotation. In this case, we
// take the second best solution, guaranteed to be a rotation. For more details,
// read the tech report: "Least-Squares Rigid Motion Using SVD", Olga Sorkine
// http://igl.ethz.ch/projects/ARAP/svd_rot.pdf
```

The code around this (lines 220 to 234) is missing from the PointToPointCovErrorMinimizer (lines 333 to 340) in ErrorMinimizersImpl.cpp.

**Comment by pomerlef** [comment]
Good catch. That gives me another argument to start refactoring `PointToPoint` functions as it happen with `PointToPlane`.

I'll try to do that sooner that later.

**Comment by artivis** [comment]
Any chance to see those lines simply copied while waiting for the refactoring :) ??

**Comment by pomerlef** [comment]
Yes, it would make sense. I'm not installed to check that on my side.

You can send a pull request if you feel comfortable with it. Otherwise, @davidlandry93 could you have a look?

**Comment by artivis** [comment]
see PR #217

**Comment by pomerlef** [comment]
Merged, thanks @artivis!
