### ISSUE TITLE
ICP for 2d point set, without knowning the corresponding pairs?

### ISSUE THREAD

**Issue by Shiying99** [ethz-asl/libpointmatcher#225]
Hi. 
I wanted to libpointmatcher for align two simple shape in image plane  in real time, one of them is a little bit noisy. 
So the corresponding pairs are not given. The points are saved as vector<Point2f> in C++.

I have some trouble to convert vector<Point2f> to DataPoint for using the library. Since i could find any detail tutorial and the given tutorial only provide sample code for reading a file of Point cloud, and in my case i want to pass the vector<Point2f> to the method.

Is there any way to do this? or alternative. Thank you very much.

**Comment by pomerlef** [comment]
You can have a look here on how to build a `datapoint` from the API:
https://github.com/ethz-asl/libpointmatcher/blob/master/utest/ui/DataPoints.cpp#L82
