### ISSUE TITLE
Libpointmatcher segfaults with latest libnabo changes

### ISSUE THREAD

**Issue by bochen87** [ethz-asl/libpointmatcher#228]
See details at https://github.com/ethz-asl/libnabo/issues/81

Summary:
Probably segfaults due to libnabo now returning -1 instead of 0 for an invalid index here: https://github.com/ethz-asl/libpointmatcher/blob/75044815d40ff934fe0bb7e05ed8bbf18c06493b/pointmatcher/OutlierFiltersImpl.cpp#L253

**Comment by HannesSommer** [comment]
Thanks for "moving" here.
 
Actually the invalid index is NNS::InvalidIndex (-1 for signed indices) : https://github.com/ethz-asl/libnabo/blob/master/nabo/nabo.h#L343. 

I'll try to propose a fix.

**Comment by bochen87** [comment]
fixed with #230
