### ISSUE TITLE
Aligning ARKit point clouds

### ISSUE THREAD

**Issue by seantempesta** [ethz-asl/libpointmatcher#231]
I've spent the past day trying to get two point clouds I've captured with Apple's ARKit to align with no success.  Using the default and the icp_tutorial_cfg configs never yielded any overlap.  I'm really out of my area of expertise here, so if anyone can hint as to a better config I'd appreciate it.

ARKit point clouds:
- 0,0,0 is where the session starts (where the phone in space)
- Don't require any scaling as all x,y,z values are in meters from the session start point
- Have a consistent Y axis aligned with gravity
- Horizontal planes are known
- The position of the camera at the time the point was captured changes over time, but is known (can I use this for "normals"?)
- Are "noisy".  Apple doesn't guarantee the number or arrangement of points between sessions will be the same
- I can get the RGBA values for the points with a little bit of work

Attached are two scans of the same room where one is more in depth (full.csv.zip) and the other is partial (partial.csv.zip).  

x,y,z = feature point location in space
nx,ny,nz = location of camera at the time the feature point was recorded

[full.csv.zip](https://github.com/ethz-asl/libpointmatcher/files/1514358/full.csv.zip)
[partial.csv.zip](https://github.com/ethz-asl/libpointmatcher/files/1514359/partial.csv.zip)

Also, is it bad that the reference filter is removing 93% of my data points because it couldn't compute normals for them?

Output from running the tutorial config on those files:
```
sean@sean-mac ~/s/l/e/csv_test> ../../build/examples/pmicp -v --config icp_tutorial_cfg.yaml full.csv partial.csv 
* KDTreeMatcher: initialized with knn=1, epsilon=0, searchType=1 and maxDist=inf
Applying 1 DataPoints filters - 349992 points in
  SamplingSurfaceNormalDataPointsFilter - Could not compute normal for 300930 pts.
* SamplingSurfaceNormalDataPointsFilter - 24446 points out (-93.0153%)
Applied 1 filters - 24446 points out (-93.0153%)
PointMatcher::icp - reference pre-processing took 0.438156 [s]
Applying 1 DataPoints filters - 604706 points in
* RandomSamplingDataPointsFilter - 302267 points out (-50.0142%)
Applied 1 filters - 302267 points out (-50.0142%)
PointMatcher::icp - reading pre-processing took 0.0458838 [s]
PointMatcher::icp - 40 iterations took 174.116 [s]
match ratio: 0.950014
writing to test_ref.vtk
writing to test_data_in.vtk
writing to test_data_out.vtk
ICP transformation:
  0.999267 -0.0248834 -0.0290917   0.744875
 0.0231882   0.998092 -0.0572228   -0.40363
 0.0304601  0.0565063   0.997937   0.972357
         0          0          0          1
```

**Comment by pomerlef** [comment]
We don't have specific experience with ARKit point clouds and support for specific applications are hard to do without the point clouds.

If you feel that the documentation is not enough to help, don't hesitate to ask for a specific topic to be covered.
