### ISSUE TITLE
[question] externally coordinating normals with ICP

### ISSUE THREAD

**Issue by svenevs** [ethz-asl/libpointmatcher#234]
Hello,

Please feel free to close without response, as this is not an issue with the library, it's me not seeing the whole picture.

1. I already have normals computed, so I should not be writing a `DataFilter`.  I should be adding a [descriptor](http://libpointmatcher.readthedocs.io/en/latest/Pointclouds/#descriptor-labels) when I create `DataPoint` objects, correct?

2. The descriptor for (1) **must** be named `"normals"`, emphasis: **`s`** at the end (if so, should I PR to add an `s` on the docs?):

    https://github.com/ethz-asl/libpointmatcher/blob/59164e766d9964255031a6b1415e4c9af558abaf/pointmatcher/ErrorMinimizers/PointToPlane.cpp#L115-L116

3. So assuming I successfully create (1) with `normals` labelled correctly, this is enough for the actual implementation to use it right?  Or is there another step to making sure these actually get used?

4. Since I'm externally specifying normals, but do need to remove NaN, I need to pre-filter the buffers I use as input positions / normals?  AKA the NaN `DataFilter` would only filter positions, but I've got data coming in where if the position was NaN, the normal is set to NaN.
    - Asked another way: if I want to externally supply normals, then I really cannot use any existing `DataFilter` objects, since whatever would get filtered here would mean that my positions dimensions and normals dimensions no longer agree?

I'm very new to this library, and most confused about (4), since it seems like that would mean the NormalsFilter must **always** be specified last, but this doesn't seem to be true, nor would it make sense because you would get very different results for the normals if you severely downsample.

Thank you for any thoughts / clarifications!

**Comment by pomerlef** [comment]
1. yes
1. yes, yes
1. yes, the manual generation of DataPoints is not well documented (lack of time). Your best documentation is the unit tests. The method `addDescriptor()` is the easiest if your `DataPoints` already exists:

   https://github.com/ethz-asl/libpointmatcher/blob/master/utest/ui/DataPoints.cpp#L323-L324

   Otherwise, a constructor with descriptor exists too: 

   https://github.com/ethz-asl/libpointmatcher/blob/master/utest/ui/DataPoints.cpp#L57

1. There are many checks to ensure that the number of points in the feature and descriptor matrix are the same. If a filter remove a point (either based on a feature or on a descriptor), both matrices are resized.

**Comment by svenevs** [comment]
Excellent, thank you very much for taking the time to confirm / explain!  The PR is on my agenda, but I think it would be nice to include a working example of this.  I was planning on doing this with just a manual point cloud being generated, the tutorial would be demonstrating both normals as well as how to use `Eigen::Map` to get things working (for both positions and normals).  I originally thought I was going to have to transpose all of my data, but it turns out I don't.

I will see how far I get on that today, and if it doesn't pan out / is too complicated for a tutorial, I'll just submit the docs PR.

> If a filter remove a point (either based on a feature or on a descriptor), both matrices are resized.

Is the inverse true (do filters process descriptors)?  It doesn't appear this way, the only one it would even make sense for is the NaN filter.  For the would-be tutorial, I was planning on computing the normals with a simple naive cross product between north / south / east / west neighbors since it is easy to understand.  I could get clever on the borders, but thought it might be better to explicitly set the borders to NaN to aid in demonstrating this.  So in this case, the positions would have all valid measurements on the borders, but since the normals descriptor has NaN on the border, the positions would now get resized?  I'm working toward this and should be able to test it, just wondering if that is the expected behavior.  I think it would be good for this would-be tutorial to demonstrate this aspect, since many normal estimation methods may not be able to "safely" compute a normal for a given neighborhood.

**Comment by pomerlef** [comment]
For the NaN, the check is here https://github.com/ethz-asl/libpointmatcher/blob/master/pointmatcher/DataPointsFiltersImpl.cpp#L93

It wouldn't cost to much to check also on `cloud.descriptors.col(i).array()` on top of `features`.

As extra, the call `cloud.setColFrom(j, cloud, i);` is the one taking care of resizing the whole point cloud (features, descriptors and time) and not just one of the matrices. Yes, there is also a matrice for time, but this is an undocumented add-on.

**Comment by svenevs** [comment]
Sounds good to me, I'll close this as resolved and send some more your way soon.  I definitely misunderstood that, I stupidly thought `cloud.setColFrom(...)` was only affecting positions.  Makes total sense now!
