### ISSUE TITLE
Passing Eigen::MatrixXf to libpointmatcher

### ISSUE THREAD

**Issue by ashnarayan13** [ethz-asl/libpointmatcher#238]
Hi, 

I already parse the csv files and store them as Eigen matrices, is there any way to pass the eigen matrix directly to the libpointmatcher? 
I do some filtering of the data before doing the ICP, hence i have them in Eigen format. 
Any leads? 

Thank you!

**Comment by pomerlef** [comment]
This is similar to #234.

Your best documentation is the unit test on DataPoints: https://github.com/ethz-asl/libpointmatcher/blob/master/utest/ui/DataFilters.cpp#L52

We are missing a bit of time for a tutorial about that topic.

**Comment by ashnarayan13** [comment]
Thank you! The unit tests helped. I will close the issue
