### ISSUE TITLE
Using PureTranslation for ICP is throwing an error

### ISSUE THREAD

**Issue by iifuzz** [ethz-asl/libpointmatcher#241]
if(this->checkParameters(parameters) == false)
	throw PointMatcherSupport::TransformationError("PureTranslation: Error, left part  not identity.");

Should it be possible to use this rather than the RigidTransformation?

**Comment by pomerlef** [comment]
So, I'm not sure what you're looking for.

Did you try to use `PureTranslation` and you received the exception `PureTranslation: Error, left part not identity.`?
