### ISSUE TITLE
DeprecationWarning.h missing after install

### ISSUE THREAD

**Issue by davidlandry93** [ethz-asl/libpointmatcher#266]
Hello all,

I think that a bug sneaked into the installation procedure.
When I build and install libpointmatcher and then try to include it from a consumer project I get

```
/home/dlandry/local/include/pointmatcher/PointMatcher.h:62:33: fatal error: DeprecationWarnings.h: No such file or directory
```

I think this might have something to do with change @lorenwel made in #210, probably just forgot to add DeprecationWarnings.h to the CMakeLists.txt.

Can anybody reproduce?

Thanks

**Comment by HannesSommer** [comment]
Thanks, @davidlandry93 , for pointing this out! Yes, this is missing. No need to reproduce since it must be installed by principle as a transitive dependency of `PointMatcher.h`. 
It should be around here https://github.com/ethz-asl/libpointmatcher/blob/master/CMakeLists.txt#L374.

**Comment by mpitropov** [comment]
@HannesSommer Would you be able to review my PR? https://github.com/ethz-asl/libpointmatcher/pull/274 The program is currently not installed correctly.
