### ISSUE TITLE
Clean the deployment with ROS package

### ISSUE THREAD

**Issue by pomerlef** [ethz-asl/libpointmatcher#293]
The bloom deployment with ROS has not been touch since a couple of years.

So much that I don't recall how to access it. Here are some generic info: http://wiki.ros.org/bloom

**Comment by simonpierredeschenes** [comment]
- [ ] Disable 32-bit build
- [ ] Configure builds to use libnabo master instead of 1.0.6
- [ ] Update dependency script to check libnabo version and verify if it was installed using apt-get
