### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by cfo** [ethz-asl/libpointmatcher#3]
Hi François  and Stéphane, 
I would like to try libpointmatcher but fail to compile it.
I use Ubuntu 11.10 and gcc version 4.6.1. 
Thanks for your help!
Here's the error:

cforster@CFoW520:~/workspace/libpointmatcher/build$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ${SRC_DIR}
-- The C compiler identification is GNU

-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Doxygen: /usr/bin/doxygen 
-- Found DOXYFILE_IN: /home/cforster/workspace/libpointmatcher/Doxyfile.in 
-- Boost version: 1.46.1
-- Found the following Boost libraries:
--   thread
--   filesystem
--   system
--   program_options
--   date_time
-- Looking for _POSIX_TIMERS
-- Looking for _POSIX_TIMERS - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cforster/workspace/libpointmatcher/build
cforster@CFoW520:~/workspace/libpointmatcher/build$ make
Scanning dependencies of target doxygen
[  0%] Writing documentation to /home/cforster/workspace/libpointmatcher/build/doc...
/home/cforster/workspace/libpointmatcher/pointmatcher/PointMatcher.h:521: warning: Member compute(const DataPoints &filteredReading, const DataPoints &filteredReference, const Matches &input) (function) of class PointMatcher::OutlierFilters is not documented.
[  2%] Built target doxygen
Scanning dependencies of target doc
[  2%] Built target doc
Scanning dependencies of target pointmatcher
[  5%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/Logger.cpp.o
[  8%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/DataPoints.cpp.o
[ 10%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/Matches.cpp.o
[ 13%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/ICP.cpp.o
[ 16%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/Registry.cpp.o
[ 18%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/DataPointsFilter.cpp.o
[ 21%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/Matcher.cpp.o
[ 24%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/OutlierFilter.cpp.o
[ 27%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/ErrorMinimizer.cpp.o
[ 29%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/Transformation.cpp.o
[ 32%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/TransformationChecker.cpp.o
[ 35%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/Inspector.cpp.o
[ 37%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/IO.cpp.o
[ 40%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/Bibliography.cpp.o
[ 43%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/Timer.cpp.o
[ 45%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/Histogram.cpp.o
[ 48%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/Parametrizable.cpp.o
[ 51%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/LoggerImpl.cpp.o
[ 54%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/DataPointsFiltersImpl.cpp.o
[ 56%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/MatchersImpl.cpp.o
/home/cforster/workspace/libpointmatcher/pointmatcher/MatchersImpl.cpp: In member function ‘typename PointMatcher<T>::Matches MatchersImpl<T>::KDTreeVarDistMatcher::findClosests(const DataPoints&) [with T = float, typename PointMatcher<T>::Matches = PointMatcher<float>::Matches, MatchersImpl<T>::DataPoints = PointMatcher<float>::DataPoints]’:
/home/cforster/workspace/libpointmatcher/pointmatcher/MatchersImpl.cpp:148:38:   instantiated from here
/home/cforster/workspace/libpointmatcher/pointmatcher/MatchersImpl.cpp:143:2: error: no matching function for call to ‘Nabo::NearestNeighbourSearch<float>::knn(const Matrix&, PointMatcher<float>::Matches::Ids&, PointMatcher<float>::Matches::Dists&, Eigen::DenseBase<Eigen::Block<const Eigen::Matrix<float, -0x00000000000000001, -0x00000000000000001>, -0x00000000000000001, -0x00000000000000001, false, true> >::ConstTransposeReturnType, const int&, const float&, Nabo::NearestNeighbourSearch<float>::SearchOptionFlags)’
/home/cforster/workspace/libpointmatcher/pointmatcher/MatchersImpl.cpp:143:2: note: candidates are:
/usr/local/include/nabo/nabo.h:291:17: note: long unsigned int Nabo::NearestNeighbourSearch<T>::knn(const Vector&, Nabo::NearestNeighbourSearch<T>::IndexVector&, Nabo::NearestNeighbourSearch<T>::Vector&, Nabo::NearestNeighbourSearch<T>::Index, T, unsigned int, T) const [with T = float, Nabo::NearestNeighbourSearch<T>::Vector = Eigen::Matrix<float, -0x00000000000000001, 1>, Nabo::NearestNeighbourSearch<T>::IndexVector = Eigen::Matrix<int, -0x00000000000000001, 1>, Nabo::NearestNeighbourSearch<T>::Index = int]
/usr/local/include/nabo/nabo.h:291:17: note:   no known conversion for argument 2 from ‘PointMatcher<float>::Matches::Ids {aka Eigen::Matrix<int, -0x00000000000000001, -0x00000000000000001>}’ to ‘Nabo::NearestNeighbourSearch<float>::IndexVector& {aka Eigen::Matrix<int, -0x00000000000000001, 1>&}’
/usr/local/include/nabo/nabo.h:304:25: note: long unsigned int Nabo::NearestNeighbourSearch<T>::knn(const Matrix&, Nabo::NearestNeighbourSearch<T>::IndexMatrix&, Nabo::NearestNeighbourSearch<T>::Matrix&, Nabo::NearestNeighbourSearch<T>::Index, T, unsigned int, T) const [with T = float, Nabo::NearestNeighbourSearch<T>::Matrix = Eigen::Matrix<float, -0x00000000000000001, -0x00000000000000001>, Nabo::NearestNeighbourSearch<T>::IndexMatrix = Eigen::Matrix<int, -0x00000000000000001, -0x00000000000000001>, Nabo::NearestNeighbourSearch<T>::Index = int]
/usr/local/include/nabo/nabo.h:304:25: note:   no known conversion for argument 4 from ‘Eigen::DenseBase<Eigen::Block<const Eigen::Matrix<float, -0x00000000000000001, -0x00000000000000001>, -0x00000000000000001, -0x00000000000000001, false, true> >::ConstTransposeReturnType {aka const Eigen::Transpose<const Eigen::Block<const Eigen::Matrix<float, -0x00000000000000001, -0x00000000000000001>, -0x00000000000000001, -0x00000000000000001, false, true> >}’ to ‘int’
/home/cforster/workspace/libpointmatcher/pointmatcher/MatchersImpl.cpp: In member function ‘typename PointMatcher<T>::Matches MatchersImpl<T>::KDTreeVarDistMatcher::findClosests(const DataPoints&) [with T = double, typename PointMatcher<T>::Matches = PointMatcher<double>::Matches, MatchersImpl<T>::DataPoints = PointMatcher<double>::DataPoints]’:
/home/cforster/workspace/libpointmatcher/pointmatcher/MatchersImpl.cpp:149:39:   instantiated from here
/home/cforster/workspace/libpointmatcher/pointmatcher/MatchersImpl.cpp:143:2: error: no matching function for call to ‘Nabo::NearestNeighbourSearch<double>::knn(const Matrix&, PointMatcher<double>::Matches::Ids&, PointMatcher<double>::Matches::Dists&, Eigen::DenseBase<Eigen::Block<const Eigen::Matrix<double, -0x00000000000000001, -0x00000000000000001>, -0x00000000000000001, -0x00000000000000001, false, true> >::ConstTransposeReturnType, const int&, const double&, Nabo::NearestNeighbourSearch<double>::SearchOptionFlags)’
/home/cforster/workspace/libpointmatcher/pointmatcher/MatchersImpl.cpp:143:2: note: candidates are:
/usr/local/include/nabo/nabo.h:291:17: note: long unsigned int Nabo::NearestNeighbourSearch<T>::knn(const Vector&, Nabo::NearestNeighbourSearch<T>::IndexVector&, Nabo::NearestNeighbourSearch<T>::Vector&, Nabo::NearestNeighbourSearch<T>::Index, T, unsigned int, T) const [with T = double, Nabo::NearestNeighbourSearch<T>::Vector = Eigen::Matrix<double, -0x00000000000000001, 1>, Nabo::NearestNeighbourSearch<T>::IndexVector = Eigen::Matrix<int, -0x00000000000000001, 1>, Nabo::NearestNeighbourSearch<T>::Index = int]
/usr/local/include/nabo/nabo.h:291:17: note:   no known conversion for argument 2 from ‘PointMatcher<double>::Matches::Ids {aka Eigen::Matrix<int, -0x00000000000000001, -0x00000000000000001>}’ to ‘Nabo::NearestNeighbourSearch<double>::IndexVector& {aka Eigen::Matrix<int, -0x00000000000000001, 1>&}’
/usr/local/include/nabo/nabo.h:304:25: note: long unsigned int Nabo::NearestNeighbourSearch<T>::knn(const Matrix&, Nabo::NearestNeighbourSearch<T>::IndexMatrix&, Nabo::NearestNeighbourSearch<T>::Matrix&, Nabo::NearestNeighbourSearch<T>::Index, T, unsigned int, T) const [with T = double, Nabo::NearestNeighbourSearch<T>::Matrix = Eigen::Matrix<double, -0x00000000000000001, -0x00000000000000001>, Nabo::NearestNeighbourSearch<T>::IndexMatrix = Eigen::Matrix<int, -0x00000000000000001, -0x00000000000000001>, Nabo::NearestNeighbourSearch<T>::Index = int]
/usr/local/include/nabo/nabo.h:304:25: note:   no known conversion for argument 4 from ‘Eigen::DenseBase<Eigen::Block<const Eigen::Matrix<double, -0x00000000000000001, -0x00000000000000001>, -0x00000000000000001, -0x00000000000000001, false, true> >::ConstTransposeReturnType {aka const Eigen::Transpose<const Eigen::Block<const Eigen::Matrix<double, -0x00000000000000001, -0x00000000000000001>, -0x00000000000000001, -0x00000000000000001, false, true> >}’ to ‘int’
make[2]: **\* [CMakeFiles/pointmatcher.dir/pointmatcher/MatchersImpl.cpp.o] Error 1
make[1]: **\* [CMakeFiles/pointmatcher.dir/all] Error 2
make: **\* [all] Error 2

**Comment by shamitb** [comment]
I get a similar error while trying to compile from catkin_ws inside a ros node the linker throws an error:
undefined reference to `Nabo::NearestNeighbourSearch ...
undefined reference to `Nabo::NearestNeighbourSearch<float, Eigen::Matrix<float, -1, -1, 0, -1, -1> >::knn(Eigen::Matrix<float, -1, 1, 0, -1, 1> const&, Eigen::Matrix<int, -1, 1, 0, -1, 1>&, Eigen::Matrix<float, -1, 1, 0, -1, 1>&, int, float, unsigned int, float) const'
collect2: error: ld returned 1 exit status

**Comment by pomerlef** [comment]
Few questions to direct us:
- What is your system (OS and version, ROS version)?
- Are you using libnabo from github?
- Did you install other libnabo versions the past?
- Are you sure that libnabo compiled fully?

**Comment by shamitb** [comment]
Yes I have libnabo.a in path NABO_LIBRARY (/usr/local/lib). ROS Indigo on Ubuntu 14.04. I took it from Github.

**Comment by pomerlef** [comment]
Do you have the same error if you try to build this node (which rely on libpointmatcher and nabo):
https://github.com/ethz-asl/ethzasl_icp_mapping/tree/hydro_devel

(use the hydro branch as the indigo one is out of date)

**Comment by shamitb** [comment]
Do I just add these to my catkin_ws and try to catkin_make?

**Comment by shamitb** [comment]
I just wanted to use the K Nearest Neighbour algo in libnabo, any other suggestions?

**Comment by pomerlef** [comment]
If that's the case, then it has nothing to do with libpointmatcher. So I'll let the folks supporting libnabo answering your [issues there ](https://github.com/ethz-asl/libnabo/issues/50).
