### ISSUE TITLE
libpointmatcher is not supported on Unbuntu 32bit

### ISSUE THREAD

**Issue by pomerlef** [ethz-asl/libpointmatcher#30]
CMake should not allow any compilation on 32bit Ubuntu.

In the current state, it compiles and some unit tests crashes with other weird bugs.

**Comment by dirk-thomas** [comment]
Also the 32bit job on the build farm fails: http://jenkins.ros.org/view/IbinT32/job/ros-indigo-libpointmatcher_binarydeb_trusty_i386/209/console
