### ISSUE TITLE
how to use libpointmatcher online

### ISSUE THREAD

**Issue by narutojxl** [ethz-asl/libpointmatcher#301]
How to use libpointmatcher online?  I see this library can use with point cloud files, such as  .csv,   .vtk,  .ply,  and .pcd.  How can i use it  with point cloud types in ros messages,  sensor_msgs/LaserScan or   sensor_msgs/PointCloud2, given by a laser sensor ?

**Comment by simonpierredeschenes** [comment]
There is a ROS stack called ethzasl_icp_mapping available here : https://github.com/ethz-asl/ethzasl_icp_mapping . It provides a real-time 2D and 3D ICP-based SLAM system. It works with point cloud types in ros messages.

**Comment by narutojxl** [comment]
Thanks a lot!
