### ISSUE TITLE
Build error on Visual Studio 2017

### ISSUE THREAD

**Issue by NahomKidane** [ethz-asl/libpointmatcher#305]
Followed build guide. However, I get errors when compiling.

**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.8.8
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional>cd C:\bin\libpo
intmatcher

C:\bin\libpointmatcher>msbuild /m:4 libpointmatcher.sln /clp:ErrorsOnly
Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

    18>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.15.26726\i
       nclude\type_traits(1271): error C2338: You've instantiated std::aligned_storage<Len, Align>
       with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15
       .8, the member type would non-conformingly have an alignment of only alignof(max_align_t). V
       S 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and br
       eaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Ple
       ase define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand th
       is message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXT
       ENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior. [C:\b
       in\libpointmatcher\pointmatcher.vcxproj]
    18>C:\Users\nkida001\Desktop\Research_Software\libpointmatcher\pointmatcher\MatchersImpl.cpp(96
       ): error C2039: 'InvalidIndex': is not a member of 'Nabo::NearestNeighbourSearch<float>' [C:
       \bin\libpointmatcher\pointmatcher.vcxproj]
    18>C:\Users\nkida001\Desktop\Research_Software\libpointmatcher\pointmatcher\MatchersImpl.cpp(96
       ): error C2065: 'InvalidIndex': undeclared identifier [C:\bin\libpointmatcher\pointmatcher.v
       cxproj]
    18>C:\Users\nkida001\Desktop\Research_Software\libpointmatcher\pointmatcher\MatchersImpl.cpp(97
       ): error C2039: 'InvalidValue': is not a member of 'Nabo::NearestNeighbourSearch<float>' [C:
       \bin\libpointmatcher\pointmatcher.vcxproj]
    18>C:\Users\nkida001\Desktop\Research_Software\libpointmatcher\pointmatcher\MatchersImpl.cpp(97
       ): error C2065: 'InvalidValue': undeclared identifier [C:\bin\libpointmatcher\pointmatcher.v
       cxproj]
    18>C:\Users\nkida001\Desktop\Research_Software\libpointmatcher\pointmatcher\MatchersImpl.cpp(14
       5): error C2039: 'InvalidIndex': is not a member of 'Nabo::NearestNeighbourSearch<float>' [C
       :\bin\libpointmatcher\pointmatcher.vcxproj]
    18>C:\Users\nkida001\Desktop\Research_Software\libpointmatcher\pointmatcher\MatchersImpl.cpp(14
       5): error C2065: 'InvalidIndex': undeclared identifier [C:\bin\libpointmatcher\pointmatcher.
       vcxproj]
    18>C:\Users\nkida001\Desktop\Research_Software\libpointmatcher\pointmatcher\MatchersImpl.cpp(14
       6): error C2039: 'InvalidValue': is not a member of 'Nabo::NearestNeighbourSearch<float>' [C
       :\bin\libpointmatcher\pointmatcher.vcxproj]
    18>C:\Users\nkida001\Desktop\Research_Software\libpointmatcher\pointmatcher\MatchersImpl.cpp(14
       6): error C2065: 'InvalidValue': undeclared identifier [C:\bin\libpointmatcher\pointmatcher.
       vcxproj]
    18>C:\Users\nkida001\Desktop\Research_Software\libpointmatcher\pointmatcher\MatchersImpl.cpp(96
       ): error C2039: 'InvalidIndex': is not a member of 'Nabo::NearestNeighbourSearch<double>' [C
       :\bin\libpointmatcher\pointmatcher.vcxproj]
    18>C:\Users\nkida001\Desktop\Research_Software\libpointmatcher\pointmatcher\MatchersImpl.cpp(97
       ): error C2039: 'InvalidValue': is not a member of 'Nabo::NearestNeighbourSearch<double>' [C
       :\bin\libpointmatcher\pointmatcher.vcxproj]
    18>C:\Users\nkida001\Desktop\Research_Software\libpointmatcher\pointmatcher\MatchersImpl.cpp(14
       5): error C2039: 'InvalidIndex': is not a member of 'Nabo::NearestNeighbourSearch<double>' [
       C:\bin\libpointmatcher\pointmatcher.vcxproj]

**Comment by simonpierredeschenes** [comment]
A new fix for Windows was merged into master and a new version of the compilation tutorial is available. Do you still have compilation errors?
