### ISSUE TITLE
Min/max datafilters are confusing to use

### ISSUE THREAD

**Issue by pomerlef** [ethz-asl/libpointmatcher#31]
The documentation seems to confuse greater than and smaller than:
https://github.com/ethz-asl/libpointmatcher/blob/master/doc/Datafilters.md#maximum-distance-filter-

Those filter should be combined and a parameter should be added to select whether we want to keep point smaller or greater than a threshold.

**Comment by simonpierredeschenes** [comment]
https://github.com/ethz-asl/libpointmatcher/pull/270
This pull request introduces the new DistanceLimitDataPointsFilter to replace both min and max distance filters.
