### ISSUE TITLE
Some question in paper

### ISSUE THREAD

**Issue by BlankCheng** [ethz-asl/libpointmatcher#316]
Hello, I had a question when reading "Comparing ICP variants on real-world data sets " about the metric of error. That is the "Given the ground truth Transformation Tg".How can we get that Tg to compare with Tr. And if we have Tg, can we just use Tg instead of using ICP?

Thanks a lot!

**Comment by simonpierredeschenes** [comment]
In the article, the ground truth was obtained from theodolite measures. In real life applications, we don't have access to those kinds of measures, which is why we use ICP.

**Comment by BlankCheng** [comment]
Many Thanks!

**Comment by BlankCheng** [comment]
May I ask one more ! What's the "match ratio" in the output of pmicp, is it an error metric? I change the modular but it barely changes. If not, is there an error metric in pmicp or other project?
Thanks a lot!

**Comment by simonpierredeschenes** [comment]
During the matching step, points from the reference cloud and from the reading cloud are matched together. This ratio is actually the number of points matched on the number of points in the reading. It *can* be used as an approximation of the error, but it is not recommended. Instead, use getResidualError from the ErrorMinimizer class to have a good approximation of the error.
