### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jprodriguezg** [ethz-asl/libpointmatcher#329]
Name 		| Version
----------------|-------------------------------
ubuntu: 	| Description: Ubuntu 16.04.6 LTS
architecture: 	| 64-bit
gcc: 		| gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
git: 		| git version 2.7.4
cmake: 		| cmake version 3.5.1 CMake suite maintained and supported by Kitware (kitware.com/cmake).
boost: 		| Version: 1.58.0.1ubuntu1
eigen3: 	| Version: 3.3~beta1-2
doxygen: 	| Version: 1.8.11-1

Hello, 

I am having an error after the last installation step of libpointmatcher (`sudo make install`). I am obtaining 3 errors related to the Gestalt.cpp file:

> ~/libpointmatcher/pointmatcher/DataPointsFilters/Gestalt.cpp:499:9: error: no match for ‘operator++’ (operand type is ‘Eigen::internal::enable_if<true, Eigen::IndexedView<Eigen::Matrix<double, -1, -1>, double, double> >::type {aka Eigen::IndexedView<Eigen::Matrix<double, -1, -1>, double, double>}’)
>          ++(numOfValues(indices(0,it), indices(1,it)));
>          ^
> ~/libpointmatcher/pointmatcher/DataPointsFilters/Gestalt.cpp:514:71: error: no match for ‘operator-’ (operand types are ‘Eigen::DenseCoeffsBase<Eigen::Matrix<double, -1, 1>, 1>::Scalar {aka double}’ and ‘Eigen::internal::enable_if<true, Eigen::IndexedView<Eigen::Matrix<double, -1, -1>, double, double> >::type {aka Eigen::IndexedView<Eigen::Matrix<double, -1, -1>, double, double>}’) 
> gestaltVariances(indices(0,it), indices(1,it)) += (heights(it)
>-gestaltMea
>  ^                                                                     
> ~/libpointmatcher/pointmatcher/DataPointsFilters/Gestalt.cpp:514:130: error: no match for ‘operator-’ (operand types are ‘Eigen::DenseCoeffsBase<Eigen::Matrix<double, -1, 1>, 1>::Scalar {aka double}’ and ‘Eigen::internal::enable_if<true, Eigen::IndexedView<Eigen::Matrix<double, -1, -1>, double, double> >::type {aka Eigen::IndexedView<Eigen::Matrix<double, -1, -1>, double, double>}’)
>  ights(it)-gestaltMeans(indices(0,it), indices(1,it))) * (heights(it)
>-gestaltMea
> ^

Could you please give me an advice to solve this issue?

Thanks,

**Comment by simonpierredeschenes** [comment]
This looks like a problem with Eigen. Maybe something went wrong when it was installed. Have you tried uninstalling it completely and reinstalling it. Maybe try with a different version of Eigen?
