### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by PhiBabin** [ethz-asl/libpointmatcher#338]
- [x] Regenerate doxygen documentation
 - [ ] Update [https://libpointmatcher.readthedocs.io](https://libpointmatcher.readthedocs.io)

**Comment by pomerlef** [comment]
Also publish the internal doc from the headers (module name, parameter ranges, etc.)

See `./examples/list_modules`

**Comment by simonpierredeschenes** [comment]
The doxygen documentation is now available here : 
 https://norlab.ulaval.ca/research/libpointmatcher/#documentation

**Comment by simonpierredeschenes** [comment]
Both stable and latest documentations were regenerated on readthedocs.io: https://libpointmatcher.readthedocs.io
