### ISSUE TITLE
Failed to build with error "You need libnabo version 1.0.7 or greater"

### ISSUE THREAD

**Issue by SubMishMar** [ethz-asl/libpointmatcher#339]
I have installed libnabo from source and while installing libpointmatcher, I get the above error. I will appreciate any help that will help me complete the installation of libpointmatcher.

**Comment by PhiBabin** [comment]
You probably have another version of libnabo installed. I suggest removing installed version of libnabo and than compiling and installing from source.

**Comment by SubMishMar** [comment]
Thanks, I removed the concerned files located in /usr/local and re-installed libnabo from source. Now libpointmatchers installs without error. Appreciate the help :).
