### ISSUE TITLE
has used multi thread?

### ISSUE THREAD

**Issue by chennuo0125** [ethz-asl/libpointmatcher#345]
when i use icp to match two pointcloud,  i found that icp process occupy three cores, whether use multi thread in icp process?  and how to achieve ?

**Comment by PhiBabin** [comment]
The main source of multithread performance in libpointmatcher is kd-tree search. We use the libnabo library for handling kd-tree computation. If you compile libnabo with the flag `USE_OPEN_MP` to true (it is the default value), it will do kd-tree seach using multiple threads.

**Comment by chennuo0125** [comment]
thank you, i get it !
