### ISSUE TITLE
how to install this library by dpkg tool? where can i get deb installation package?

### ISSUE THREAD

**Issue by chennuo0125** [ethz-asl/libpointmatcher#346]

**Comment by PhiBabin** [comment]
There are no up to date .deb package for libpointmatcher.
However, it should be [relatively easy to create a .deb](https://ubuntuforums.org/showthread.php?t=910717) for each release using our Jenkins/travis.

**Comment by chennuo0125** [comment]
thanks, i am trying your suggestion.
