### ISSUE TITLE
what():  RigidTransformation: Error, rotation matrix is not orthogonal.

### ISSUE THREAD

**Issue by chennuo0125** [ethz-asl/libpointmatcher#349]
i use this library to match lidar cloud to map during localization process, when i set  
```
errorMinimizer:PointToPlaneErrorMinimizer  
```
every is ok !  
but when i set  
```
errorMinimizer:PointToPointErrorMinimizer  
```
program crushed and print "Error, rotation matrix is not orthogonal."  
why?

**Comment by jstiefel** [comment]
Independent of why you get a non-orthogonal rotation matrix, you might want to use `checkParameters` and `correctParameters` of `TransformationsImpl` to solve your issue:

http://docs.ros.org/hydro/api/libpointmatcher/html/structTransformationsImpl_1_1RigidTransformation.html
