### ISSUE TITLE
Tutorial page "Creating a DataPointsFilter" at readthedocs.io has a problem with formatting

### ISSUE THREAD

**Issue by kubelvla** [ethz-asl/libpointmatcher#373]
The problem is on the page https://libpointmatcher.readthedocs.io/en/latest/DataPointsFilterDev/ in the section "Generic procedure". The list of steps a has a funky format, probably an issue with markdown?

**Comment by AlexandreG87** [comment]
The problem is that to properly display a nested code block in a list, it must be indented using 4 spaces or 1 tab without using the code fencing (\``` code \```) syntax. The list numbering is also affected by this syntax, it restart to 1 after each block.
