### ISSUE TITLE
Running utest failure

### ISSUE THREAD

**Issue by ryleymcc** [ethz-asl/libpointmatcher#425]
following [this](https://github.com/ethz-asl/libpointmatcher/blob/master/doc/CompilationUbuntu.md#possible-caveats) tutorial to install libpointmatcher. 

when i run 

ryley@ryley-GL65-9SD:~/Libraries/libpointmatcher$ utest/utest --path ${SRC_DIR}/examples/data/

i get this

terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot open file /examples/data/2D_oneBox.csv
Aborted (core dumped)

also this`

`
ryley@ryley-GL65-9SD:~/Libraries/libpointmatcher$ ./utest/listVersionsUbuntu.sh

 Copy-paste those information when reporting a bug in libpointmatcher:

Name 		| Version
----------------|-------------------------------
ubuntu: 	| Description: Ubuntu 20.04.1 LTS
architecture: 	| 64-bit
gcc: 		| gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
git: 		| git version 2.25.1
cmake: 		| cmake version 3.16.3 CMake suite maintained and supported by Kitware (kitware.com/cmake).
boost: 		| Version: 1.71.0.0ubuntu2
eigen3: 	| Version: 3.3.7-2
doxygen: 	| Version: 1.8.17-0ubuntu2
``

>

**Comment by ryleymcc** [comment]
i should add that this is a new install of Ubuntu 20.04 LTS

**Comment by pomerlef** [comment]
What is in your variable `${SRC_DIR}`?

If you want you can navigate in the repo and search for the folder `data` and use that path after the flag `--path`. The folder exist here: https://github.com/ethz-asl/libpointmatcher/tree/master/examples/data

**Comment by AlexandreG87** [comment]
Hi @ryleymcc! Did you manage to run the tests? If not, you must be in the build directory in order to be able to execute that command. You can also replace the `${SRC_DIR}/examples/data/` part by `../examples/data/`, since the variable `SRC_DIR` needs to be define every time a new terminal is opened.

**Comment by ryleymcc** [comment]
I have switched my projects strategy and this is no longer an issue of mine. I will close this issue now.
