### ISSUE TITLE
Narrowing conversion on windows

### ISSUE THREAD

**Issue by maxGimeno** [ethz-asl/libpointmatcher#469]
I get 
```
libpointmatcher\pointmatcher\DataPointsFilters\MaxPointCount.cpp(73,42): error C2398: Element '1': conversion from 'size_t' to 'unsigned int' requires a  a narrowing conversion
```
When building with MSVC 2019 on Windows.

**Comment by lrineau** [comment]
The culprit is fad06b95a5c3b55a27956268a4eb5247c2822a06, that changed the type of `seed` from `unsigned int` to `std::size_t`. I am surprised that it compiles correctly on any C++11 platform.

**Comment by pomerlef** [comment]
Good catch! @maxGimeno Are you organized to send a PR and validate it on Windows?

**Comment by maxGimeno** [comment]
@pomerlef  done

**Comment by pomerlef** [comment]
Thanks!
