### ISSUE TITLE
ROS release for noetic and galactic

### ISSUE THREAD

**Issue by Timple** [ethz-asl/libpointmatcher#483]
Thank you for creating this package!

It's a dependency of rtabmap.

Are there any objections if I release it to the ROS buildfarm?
Of course also pending the outcome of https://github.com/ethz-asl/libnabo/issues/117

**Comment by pomerlef** [comment]
All good on my side. Could you post related links to the buildfarm here so we can track what is going on?

**Comment by Timple** [comment]
Great, I'll wait for #482 first. As that won't be release-able for ROS2.
