### ISSUE TITLE
Loop counter variable used twice

### ISSUE THREAD

**Issue by simonpierredeschenes** [ethz-asl/libpointmatcher#489]
The variable `i` is used as a counter in both the outer and inner loops.

https://github.com/ethz-asl/libpointmatcher/blob/c0d13ea87d3f6ccb81cbf0f9dc02a118a0c42f03/pointmatcher/DataPointsFilters/SurfaceNormal.cpp#L205

**Comment by HS7499** [comment]
Hii Simon, Can I work on this issue?

**Comment by simonpierredeschenes** [comment]
Hi @HS7499 ,  yes you can work on it, it would be very appreciated! You can assign me to review the PR when you create it. Thanks! :)

**Comment by pomerlef** [comment]
Solved with #521
