### ISSUE TITLE
Undefined symbols for architecture x86_64:   "Nabo::NearestNeighbourSearch<double, Eigen::Matrix<doubl...

### ISSUE THREAD

**Issue by drhalftone** [ethz-asl/libpointmatcher#514]
I'm running the following:

Mac OS X version 12.6.6
gcc version Apple clang version 14.0.0 (clang-1400.0.29.202)
Homebrew 4.0.20
boost: stable 1.81.0 (bottled), HEAD
git version 2.40.1
cmake version 3.26.4
eigen: stable 3.4.0 (bottled), HEAD

Followed directions for Mac OS X and got down to this when making libpointmatcher:

[ 92%] Linking CXX executable icp_simple
Undefined symbols for architecture x86_64:
  "Nabo::NearestNeighbourSearch<double, Eigen::Matrix<double, -1, -1, 0, -1, -1> >::create(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, int, Nabo::NearestNeighbourSearch<double, Eigen::Matrix<double, -1, -1, 0, -1, -1> >::SearchType, unsigned int, Nabo::Parameters const&)", referenced from:
      MatchersImpl<double>::KDTreeMatcher::init(PointMatcher<double>::DataPoints const&) in libpointmatcher.a(MatchersImpl.cpp.o)
      MatchersImpl<double>::KDTreeVarDistMatcher::init(PointMatcher<double>::DataPoints const&) in libpointmatcher.a(MatchersImpl.cpp.o)
      TensorVoting<double>::computeKnn(PointMatcher<double>::DataPoints const&) in libpointmatcher.a(Saliency.cpp.o)
      TensorVoting<double>::computeKnn(PointMatcher<double>::DataPoints const&) in libpointmatcher.a(SpectralDecomposition.cpp.o)
  "Nabo::NearestNeighbourSearch<float, Eigen::Matrix<float, -1, -1, 0, -1, -1> >::create(Eigen::Matrix<float, -1, -1, 0, -1, -1> const&, int, Nabo::NearestNeighbourSearch<float, Eigen::Matrix<float, -1, -1, 0, -1, -1> >::SearchType, unsigned int, Nabo::Parameters const&)", referenced from:
      MatchersImpl<float>::KDTreeMatcher::init(PointMatcher<float>::DataPoints const&) in libpointmatcher.a(MatchersImpl.cpp.o)
      MatchersImpl<float>::KDTreeVarDistMatcher::init(PointMatcher<float>::DataPoints const&) in libpointmatcher.a(MatchersImpl.cpp.o)
      TensorVoting<float>::computeKnn(PointMatcher<float>::DataPoints const&) in libpointmatcher.a(Saliency.cpp.o)
      TensorVoting<float>::computeKnn(PointMatcher<float>::DataPoints const&) in libpointmatcher.a(SpectralDecomposition.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by pomerlef** [comment]
It seems related to `libnabo` not being found. Any idea what changed in your build procedure?

**Comment by drhalftone** [comment]
Worked totally fine on my Mac Book Pro running 13.4 but not on my old trashcan Mac.  Is it possible it sees an old copy of libnabo from a previous libpointmatcher build from a few years ago?



On Jun 6, 2023, at 8:17 PM, François Pomerleau ***@***.***> wrote:


It seems related to libnabo not being found. Any idea what changed in your build procedure?

**Comment by Brac24** [comment]
I'm having a similar issue. I'm building a docker image for ARM. But I ran this same thing about a month ago with no issues. Now it looks like it has issues compiling the examples.
![image](https://github.com/ethz-asl/libpointmatcher/assets/4980091/1f50d425-9243-4d5a-894d-9cd62b4f4944)

At the start of the compilation it says libnabo found. Is there an environment variable or CMake flag that needs to be set?

**Comment by Brac24** [comment]
Sure enough it did build if I don't build the examples using the cmake flag -DPOINTMATCHER_BUILD_EXAMPLES=OFF
So there's something specific with the examples that it can't find libnabo maybe?

**Comment by pomerlef** [comment]
@drhalftone can you check if the proposed PR #513 resolve your issue?

**Comment by Brac24** [comment]
That seems to have worked for me hopefully it works for @drhalftone

**Comment by pomerlef** [comment]
Should be resolved with #513
