### ISSUE TITLE
libpointmatcherConfig.cmake has wrong paths

### ISSUE THREAD

**Issue by v01d** [ethz-asl/libpointmatcher#60]
When installing libpointmatcher, the paths generated in this file, are the ones used during installation explicitly. This means that package managers, when creating the ros-indigo-libpointmatcher package will have hard-coded paths to temporary build paths instead of final installation paths.

Example:
```
# - Config file for the libpointmatcher package
# It defines the following variables
#  libpointmatcher_INCLUDE_DIRS - include directories for pointmatcher
#  libpointmatcher_LIBRARIES    - libraries to link against
 
# Compute paths
get_filename_component(POINTMATCHER_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
set(libpointmatcher_INCLUDE_DIRS "/home/v01d/pkgs/ros/arch-ros-stacks/indigo/libpointmatcher/src/libpointmatcher/contrib/yaml-cpp-pm/include;/home/v01d/pkgs/ros/arch-ros-stacks/indigo/libpointmatcher/src/libpointmatcher;/usr/include/eigen3;/opt/ros/indigo/include;/usr/include")
  
set(libpointmatcher_LIBRARIES "/home/v01d/pkgs/ros/arch-ros-stacks/indigo/libpointmatcher/src/build//libpointmatcher.so;/opt/ros/indigo/lib/libnabo.a;/usr/lib64/libboost_thread.so;/usr/lib64/libboost_filesystem.so;/usr/lib64/libboost_system.so;/usr/lib64/libboost_program_options.so;/usr/lib64/libboost_date_time.so;/usr/lib64/libboost_chrono.so;rt")

# This causes catkin simple to link against these libraries
set(libpointmatcher_FOUND_CATKIN_PROJECT true)
```

**Comment by pomerlef** [comment]
Thanks Matias for reporting. I checked those files for standalone build but not for Catkin build. I'm still on Fuerte for legacy reasons and most of the catkinization were done by externals. It would be faster If you could submit a Pull Request  for that. Otherwise, I'll fix it, but in few months.

Cheers!

**Comment by pomerlef** [comment]
hi,

I'm not sure if it helped, but I corrected some bugs related to missing dependencies. In theory, you can use the CMake command `find_package(libpointmatcher REQUIRED)` to give you all the necessary information.

For an example, see this [CMakeList.txt](https://github.com/ethz-asl/libpointmatcher/blob/master/examples/demo_external_link/CMakeLists.txt). This example is now in the sources, so you can try it for yourself.

**Comment by v01d** [comment]
I've tried locally installing libpointmatcher and now correct paths show up
on libpointmatcherConfig.cmake, so I believe it is working now.
