### ISSUE TITLE
installing YAML-pm into /usr/local/lib/ directory...

### ISSUE THREAD

**Issue by drhalftone** [ethz-asl/libpointmatcher#66]
How do I install the YAML static library into the /usr/local/lib directory?  I can use sudo make install for NABO and PM, but what about YAML?

**Comment by drhalftone** [comment]
Obviously, I can manually copy it, but is there a sudo make install like script to install it along with libpointmatcher.a?

**Comment by pomerlef** [comment]
This library was packaged recently and it seems that there is not installation target...

I'll look into that in the next days.
