### ISSUE TITLE
cmake error when building libpointmatcher

### ISSUE THREAD

**Issue by lligen** [ethz-asl/libpointmatcher#74]
[ 40%] Building CXX object CMakeFiles/pointmatcher.dir/pointmatcher/InspectorsImpl.cpp.o
make[2]: *** No rule to make target `contrib/yaml-cpp-pm/libyaml-cpp-pm.a', needed by `libpointmatcher.so.1.2.1'.  Stop.
make[1]: *** [CMakeFiles/pointmatcher.dir/all] Error 2
make: *** [all] Error 2

**Comment by HannesSommer** [comment]
This should be solved by PR #71. Maybe you can try that branch (fix/pointmatcherTargetDoesNotDependOnYamlPm, c9ba199bd3ba43b1be37bdce2d5af5523984556d) as a quick solution?

**Comment by pomerlef** [comment]
This should be solved with the latest merge.
