### ISSUE TITLE
Build_map.cpp runtime error

### ISSUE THREAD

**Issue by jayden118** [ethz-asl/libpointmatcher#75]
Hi all,

I'm trying to run the build_map.cpp in terminal but it shows up this error:

![image](https://cloud.githubusercontent.com/assets/7490505/6664582/7ecafa5e-cc14-11e4-9091-23c268c0e654.png)

From my understanding I guess these two line cause the problem. 
![image](https://cloud.githubusercontent.com/assets/7490505/6664609/b68c78fa-cc14-11e4-91db-deb4a0683498.png)

May I know how to solve this issue?

Thank you in advanced.

Regards,
Jayden

**Comment by pomerlef** [comment]
good catch. This example is outdated (2012). I'll fix it tomorrow.

**Comment by jayden118** [comment]
Hi pomerlef,

I'll wait for your solution. Thank you very much.

Regards,
Jayden

**Comment by pomerlef** [comment]
Many things were outdated in that example. It should be solved with the latest commit.

**Comment by pomerlef** [comment]
I will assume that it's working. Just reopen if there is something

**Comment by jayden118** [comment]
Hi powerlef,

Yes. The updated code is working perfectly now. 

Thank you very much.

Regards,
Jayden
