### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by tim30235** [ethz-asl/libpointmatcher#80]
The step "Build libpointmatcher"
I got some cmake error but don't know how to fix it
![libpointmatcher_cmake_error](https://cloud.githubusercontent.com/assets/5534867/7152839/55bb267a-e375-11e4-9f35-11125c39379f.jpg)
![libpointmatcher_cmake_error2](https://cloud.githubusercontent.com/assets/5534867/7152850/8f946190-e375-11e4-947c-560ef9202c7d.jpg)
is there anything wrong??

**Comment by pomerlef** [comment]
The error lines in your error doesn't fit the current sources.

Please update to the latest version. Some of those problems were already resolved recently.

We only do limited support for Windows. On my side I can only access to an Ubuntu and Mac systems. But, if you have other problems, don't hesitate to post.

**Comment by tim30235** [comment]
Hi~
I've tried the latest version and got the same error messages.
"Unable to find the requested Boost libraries." while building on the other notebook with Win7.
Should I change any path or dir in CMakeList.txt ?

**Comment by HannesSommer** [comment]
To me it seems to be mostly warnings from a very recent CMake (this should interest us at some point). 

The only error (concerning yaml-cpp) is caused in https://github.com/ethz-asl/libpointmatcher/blob/master/contrib/yaml-cpp-pm/CMakeLists.txt#L182. Apparently the target renaming has not been executed completely.

PR #84 should solve this, but I can't test it.

**Comment by pomerlef** [comment]
Please `git pull` again. The patch was integrated to the main branch.
