### ISSUE TITLE
Wrong project name in the "Linking Projects to libpointmatcher" tutorial

### ISSUE THREAD

**Issue by davidlandry93** [ethz-asl/libpointmatcher#88]
The tutorial indicates to use "find_package(pointmatcher 1.1.0 REQUIRED)",
however the line "find_package(libpointmatcher 1.1.0 REQUIRED)" worked for me.

I built the project from source, and am using ubuntu 12.04.

**Comment by pomerlef** [comment]
Good catch. The documentation has been updated.

There is now a working cmake example here: https://github.com/ethz-asl/libpointmatcher/tree/master/examples/demo_cmake

Thanks
