### ISSUE TITLE
segfault when opening a PCD file

### ISSUE THREAD

**Issue by davidlandry93** [ethz-asl/libpointmatcher#93]
Running the following line of code
```
PointMatcher<float>::DataPoints dp = PointMatcher<float>::DataPoints::load("sample.pcd");
```
results in a segfault. I'll try using VTK files as a workaround.

**Comment by pomerlef** [comment]
Could you provide a small example pcd file that make it break?

**Comment by davidlandry93** [comment]
I was just remembered by Sebastien Michaud that binary PCD files are not supported. Sorry about that!
