### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by bhack** [ethz-asl/libpointmatcher#96]
Is this really buildabile for Android target? I see some boost dependencies in libnao and here that could be a little bit heave to resolve under Android.

**Comment by pomerlef** [comment]
Where have you seen that we are supporting Android builds?

Libpointmatcher is developed on Ubuntu, is supported on MacOs and was ported once in the past on Windows. There is no plan to port it on mobile devices unless a new developer join actively the project to do so.

**Comment by bhack** [comment]
No it wasn't declared. I only see that that there are no main problem to run this on android other than boost dependencies.  I will try to build it with https://github.com/MysticTreeGames/Boost-for-Android

**Comment by EthanGreen75** [comment]
@bhack hello, did you build this successfully on android ? I want to build it too.
