### ISSUE TITLE
How to construct 3D map continously

### ISSUE THREAD

**Issue by jayden118** [ethz-asl/libpointmatcher#97]
Hi, 

I have compiled all the source code successfully and the example codes are working fine. However, I want to use the library for constructing 3D map continuously using laser scanner data. It similar to Project: NIFTi: railyard mapping. I have tried the align_sequence code by using the ASL datasets for testing. However, the final 3D map is not aligned. Should I use icpsequence instead? Or can you guys please give me some hints on how to achieve this work?

Thank you very much.

Regards,
Jayden

**Comment by pomerlef** [comment]
Hi Jayden,

Those results as been achieved using the ROS node [ethzasl_icp_mapping](http://wiki.ros.org/ethzasl_icp_mapping), which rely on this library but also do several checks and other computation to help the mapping process.

To date, there is no registration solution that won't need any tuning to make it work. Those tuning often depend of your application. If you're interested, we just published a review on different ICP solutions (not all in the library) with some use cases (NIFTi is part of it) and some hints on how to tune your solution:

François Pomerleau, Francis Colas and Roland Siegwart (2015), "A Review of Point Cloud Registration Algorithms for Mobile Robotics", Foundations and Trends® in Robotics: Vol. 4: No. 1, pp 1-104. http://dx.doi.org/10.1561/2300000035

If you don't have access to the journal, you can download it [here](https://www.researchgate.net/publication/277558596_A_Review_of_Point_Cloud_Registration_Algorithms_for_Mobile_Robotics).

Cheers!
