### ISSUE TITLE
MaxDistOutlierFilter maxDist squared

### ISSUE THREAD

**Issue by tneukom** [ethz-asl/libpointmatcher#98]
In OutlierFiltersImpl.h it says: "This filter considers as outlier links whose norms are above a fix threshold." and the maxDist parameter is described as "threshold distance"

and is implemented like this:
```C++
return OutlierWeights((input.dists.array() <= maxDist).template cast<T>());
```

But according to PointMatcher.h:
```C++
struct Matches
{
...
	Dists dists; //!< squared distances to closest points
...
};
```
dists stores the squared distances, so shouldn't MaxDistOutlierFilter use maxDist^2 to compare?

**Comment by pomerlef** [comment]
Good catch. It as been resolved with the latest commit. See https://github.com/ethz-asl/libpointmatcher/commit/1c9400e245d7b9c471f91228a8b25ca8244e45a6 for more details

I also added in the filter doc that the parameter is related to the Euclidean norm to avoid confusion.
