### ISSUE TITLE
Cannot find Eigen dependencies...

### ISSUE THREAD

**Issue by antithing** [ethz-asl/libpointmatcher#99]
Hi, I am trying to build libpointmatcher on windows, I have Eigen, i add the path in the cmake gui, and even though the 'Core' file that it is looking for is there, it gives these errors:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
EIGEN_INCLUDE_DIR
   used as include directory in directory D:/VIRT/localisation/libpointmatcher-master/libpointmatcher-master
   used as include directory in directory D:/VIRT/localisation/libpointmatcher-master/libpointmatcher-master
   used as include directory in directory D:/VIRT/localisation/libpointmatcher-master/libpointmatcher-master/examples
   used as include directory in directory D:/VIRT/localisation/libpointmatcher-master/libpointmatcher-master/examples
   used as include directory in directory D:/VIRT/localisation/libpointmatcher-master/libpointmatcher-master/examples
   used as include directory in directory D:/VIRT/localisation/libpointmatcher-master/libpointmatcher-master/examples
   used as include directory in directory D:/VIRT/localisation/libpointmatcher-master/libpointmatcher-master/examples
   used as include directory in directory D:/VIRT/localisation/libpointmatcher-master/libpointmatcher-master/examples
   used as include directory in directory D:/VIRT/localisation/libpointmatcher-master/libpointmatcher-master/utest

Even when i remove these lines from CmakeLists.txt:

find_path(EIGEN_INCLUDE_DIR /Eigen/Core
	/usr/local/include/eigen3
	/usr/include/eigen3
)
include_directories(${EIGEN_INCLUDE_DIR})

The same errors. Is there a way that i can I just build without Eigen and re-link in the visual studio sln?

thanks!

**Comment by pomerlef** [comment]
I believe that this problem should be covered in the [revised version of the building documentation for Windows](https://github.com/ethz-asl/libpointmatcher/blob/master/doc/CompilationWindows.md).
